<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Exporter
    |--------------------------------------------------------------------------
    |
    | This option controls the default exporter that will be used by the
    | `export` method of the Excel facade. You can set this to the class
    | name of your preferred exporter.
    |
    */

    'exporter' => \Maatwebsite\Excel\Concerns\FromCollection::class,

    /*
    |--------------------------------------------------------------------------
    | Default Reader
    |--------------------------------------------------------------------------
    |
    | This option controls the default reader that will be used when using
    | the `import` method of the Excel facade. You can set this to the
    | class name of your preferred reader.
    |
    */

    'reader' => \Maatwebsite\Excel\Concerns\FromCollection::class,

    /*
    |--------------------------------------------------------------------------
    | Temporary Path
    |--------------------------------------------------------------------------
    |
    | Here you may specify the storage path used for temporary files
    | generated by Maatwebsite\Excel. The default is set to the
    | default storage path for your application.
    |
    */

    'temporary_path' => storage_path('app'),

  

];
